name: collapsible_navigation_drawer_example
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  image_picker: ^0.8.5
  sqflite: any
  path: any
  flutter:
    sdk: flutter
  flutter_slidable: 0.6.0
  carousel_slider: ^4.1.1
  smooth_page_indicator: ^0.3.0-nullsafety.0
  achievement_view: ^1.0.0
  liquid_pull_to_refresh: ^3.0.0


  cupertino_icons: ^1.0.2

  provider: ^5.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/